export default {
    LOAD: "load",
    BOOT: "boot",
    MENU: "main-menu",
    PAUSE_MENU: "pause-menu",
    MAIN_MENU: "main-menu",
    CREDITS_MENU: "credits-menu",
    LEVEL_SELECT_MENU: "level-select-menu",
    DEMO: "demo",
    WELCOME: "welcome",
    LEVEL_ONE:'levelone',
    ERROR: "error",
    ALERT:"alert",
    JUMBOTRON:"jumbotron",
    TEXT_CONSOLE:"text-console",
    BACKGROUND:"background",
}